# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, ... }:

{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
      ./firewall.nix
      ./systemd.nix
    ];

  # Bootloader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  
  # ZFS Stuff
  boot.supportedFilesystems = [ "zfs" "xfs" ];
  # boot.kernelPackages = config.boot.zfs.package.latestCompatibleLinuxPackages;

  # ZFS Pool cfg
  boot.zfs.forceImportRoot = false;
  boot.zfs.extraPools = [ "tbpool" ];

  networking.hostName = "orion";
  networking.hostId = "1412667a"; # Generated by `head -c8 /etc/machine-id`
  networking.wireless.enable = false;  # Enables wireless support via wpa_supplicant.

  # Enable networking
  networking.networkmanager.enable = true;

  # Set your time zone.
  time.timeZone = "Asia/Kolkata";

  # Select internationalisation properties.
  # i18n.defaultLocale = "en_IN";

  # i18n.extraLocaleSettings = {
  #   LC_ADDRESS = "en_IN";
  #   LC_IDENTIFICATION = "en_IN";
  #   LC_MEASUREMENT = "en_IN";
  #   LC_MONETARY = "en_IN";
  #   LC_NAME = "en_IN";
  #   LC_NUMERIC = "en_IN";
  #   LC_PAPER = "en_IN";
  #   LC_TELEPHONE = "en_IN";
  #   LC_TIME = "en_IN";
  # };

  # Enable the X11 windowing system.
  # services.xserver.enable = true;

  # Enable the GNOME Desktop Environment.
  # services.xserver.displayManager.gdm.enable = true;
  # services.xserver.desktopManager.gnome.enable = true;

  # Configure keymap in X11
  # services.xserver.xkb = {
  #   layout = "us";
  #   variant = "";
  # };

  # Set fish shell as default for all users
  programs.fish.enable = true;
  users.defaultUserShell = pkgs.fish;

  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.groups.nick.gid = 1000;
  users.users.nick = {
    isNormalUser = true;
    group = "nick";
    extraGroups = [ "networkmanager" "wheel" "docker" ];
    packages = with pkgs; [
    #  thunderbird
    ];
  };

  # Neovim with aliases systemwide
  programs.neovim = {
    enable = true;
    defaultEditor = true;
    viAlias = true;
    vimAlias = true;
  };

  # List packages installed in system profile. To search, run:
  # $ nix search wget
  environment.systemPackages = with pkgs; [
    restic
    rclone
    tmux
    zfs
    dig
    wget
    inetutils
    tree
    unzip
    zoxide
    jq
    fzf
    zip
    bat
    btop
    intel-gpu-tools
    smartmontools
    pciutils
    git
    gcc
    htop 
    python3Full
    python3Packages.pip
    python3Packages.argcomplete
    python3Packages.virtualenv
    python3Packages.setuptools-rust
  ];

  # List services that you want to enable:
  services.openssh = {
    enable = true;
    ports = [ 22 ];
    settings = {
      PasswordAuthentication = false;
      AllowUsers = [ "root" "nick" ];
      PermitRootLogin = "prohibit-password";
    };
  };

  # Tailscale config
  services.tailscale = {
    enable = true;
    useRoutingFeatures = "server";
    # extraUpFlags = "--advertise-routes=10.29.74.0/29 --accept-dns=false";
  };

  services.btrfs = {
    autoScrub = {
      enable = true;
      interval = "weekly";
    };
  };

  services.zfs = {
    autoScrub = {
      enable = true;
      interval = "weekly";
    };
    trim = {
      enable = true;
    };
  };

  virtualisation.docker = {
    enable = true;
    daemon = {
      settings = {
        "experimental" = true;
        "ipv6" = true;
        "ip6tables" = false;
        "iptables" = false;
        "dns" = [ "1.1.1.1" "1.0.0.1" ];
        "fixed-cidr-v6" = "2974:abc:1::/64";
      };
    };
  };

  # NixOS GC config
  nix.optimise.automatic = true;
  nix.gc = {
    automatic = true;
    dates = "weekly";
    options = "--delete-older-than 30d";
  };


  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It‘s perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "24.11"; # Did you read the comment?

}
