# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, ... }:

{
  imports = [
    # Include the results of the hardware scan.
    ./hardware-configuration.nix
    ./packages.nix
    ./firewall.nix
    ./systemd.nix
    ./msmtp.nix
  ];

  # Bootloader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # ZFS Stuff
  boot.supportedFilesystems = [
    "zfs"
    "xfs"
  ];
  # boot.kernelPackages = config.boot.zfs.package.latestCompatibleLinuxPackages;

  # ZFS Pool cfg
  boot.zfs.forceImportRoot = false;
  boot.zfs.extraPools = [ "tbpool" ];

  networking.hostName = "orion";
  networking.hostId = "1412667a"; # Generated by `head -c8 /etc/machine-id`
  networking.wireless.enable = false; # Enables wireless support via wpa_supplicant.
  networking.tempAddresses = "disabled";

  # Enable networking
  networking.networkmanager.enable = true;

  # Set your time zone.
  time.timeZone = "Asia/Kolkata";

  # Set fish shell as default for all users
  programs.fish.enable = true;
  users.defaultUserShell = pkgs.fish;

  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.groups.nick.gid = 1000;
  users.users.nick = {
    isNormalUser = true;
    group = "nick";
    extraGroups = [
      "networkmanager"
      "wheel"
      "docker"
    ];
    packages = with pkgs; [
      #  thunderbird
    ];
  };

  # Neovim with aliases systemwide
  programs.neovim = {
    enable = true;
    defaultEditor = true;
    viAlias = true;
    vimAlias = true;
  };

  # List services that you want to enable:
  services.openssh = {
    enable = true;
    ports = [ 22 ];
    settings = {
      PasswordAuthentication = false;
      AllowUsers = [
        "root"
        "nick"
      ];
      PermitRootLogin = "prohibit-password";
    };
  };

  # Tailscale config
  services.tailscale = {
    enable = true;
    useRoutingFeatures = "server";
    # extraUpFlags = "--advertise-routes=10.29.74.0/29 --accept-dns=false";
  };

  services.btrfs = {
    autoScrub = {
      enable = true;
      interval = "weekly";
    };
  };

  services.zfs = {
    autoScrub = {
      enable = true;
      interval = "weekly";
    };
    trim = {
      enable = true;
    };
  };

  services.smartd = {
    enable = true;
    autodetect = true;
    notifications = {
      # test = true;
      mail = {
        sender = "msmtp@mailer.srv01-prod.ydvnick.cc";
        recipient = "notify@home.lab";
      };
    };
  };

  virtualisation.docker = {
    enable = true;
    daemon = {
      settings = {
        "experimental" = true;
        "ipv6" = true;
        # "ip6tables" = false;
        # "iptables" = false;
        "dns" = [
          "1.1.1.1"
          "1.0.0.1"
        ];
        "fixed-cidr-v6" = "2974:abc:1::/64";
      };
    };
  };

  # NixOS GC config
  nix.optimise.automatic = true;
  nix.gc = {
    automatic = true;
    dates = "weekly";
    options = "--delete-older-than 30d";
  };

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It‘s perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "24.11"; # Did you read the comment?

}
